# Generated by Django 4.2.3 on 2023-10-06 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0083_workflowcontenttype'),
        ('sportsblog', '0002_sportstag_alter_blogdetailpage_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogTagPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
            ],
            options={
                'verbose_name': 'Blog Tag',
            },
            bases=('wagtailcore.page',),
        ),
    ]
