# Generated by Django 4.2.3 on 2023-10-06 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportsblog', '0003_blogtagpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogtagpage',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
