# Generated by Django 4.2.3 on 2023-09-25 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_delete_tag_alter_blogcategory_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogcategory',
            options={'verbose_name': 'Copywriting Blog Category', 'verbose_name_plural': 'Copywriting Blog Categories'},
        ),
        migrations.AlterModelOptions(
            name='blogpage',
            options={'verbose_name': 'Copywriting Blog', 'verbose_name_plural': 'Copywriting Blog'},
        ),
        migrations.AlterModelOptions(
            name='blogtagindexpage',
            options={'verbose_name': 'Tag'},
        ),
    ]
