# Generated by Django 4.2.3 on 2023-09-14 21:54

from django.db import migrations, models
import django.db.models.deletion
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
        ('wagtailcore', '0083_workflowcontenttype'),
        ('site_settings', '0002_remove_sitesettings_page_ptr_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(blank=True, help_text='Your website name', max_length=100, null=True)),
                ('caption', models.CharField(blank=True, max_length=250, null=True)),
                ('show_in_menu_bar', models.BooleanField(blank=True, default=False, help_text='Select to show logo in menu bar', null=True, verbose_name='Menu Logo')),
                ('show_title_in_menu_bar', models.BooleanField(blank=True, default=False, help_text='Select to show Title in menu bar', null=True, verbose_name='Menu Title')),
                ('links', wagtail.fields.StreamField([('link', wagtail.blocks.StructBlock([('code', wagtail.blocks.TextBlock(required=False))]))], blank=True, null=True, use_json_field=True)),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
                ('site_logo', models.ForeignKey(blank=True, help_text='Your website logo', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Site Setting',
            },
        ),
    ]
