# Generated by Django 4.2.3 on 2023-09-14 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0003_sitesettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='show_in_menu_bar',
            field=models.BooleanField(blank=True, default=False, help_text='Select to show logo in menu bar', verbose_name='Menu Logo'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='show_title_in_menu_bar',
            field=models.BooleanField(blank=True, default=False, help_text='Select to show Title in menu bar', verbose_name='Menu Title'),
        ),
    ]
