# Generated by Django 4.2.3 on 2023-09-22 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0004_alter_sitesettings_show_in_menu_bar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='links',
            field=models.TextField(blank=True, help_text='Use this to add links, scripts such as google analytics to the head section of the website', null=True, verbose_name='Links'),
        ),
    ]
