# Generated by Django 4.2.3 on 2023-09-29 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
        ('site_settings', '0005_alter_sitesettings_links'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminSiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_site_name', models.CharField(blank=True, help_text='Your website name', max_length=100, null=True)),
                ('admin_site_logo', models.ForeignKey(blank=True, help_text='Admin logo', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Admin Site Settings',
            },
        ),
    ]
